import './_css/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-white flex`}>
        {/* {props.children} */}
        {props.player1}
        {props.player2}
      </body>
    </html>
  )
}
